# Generated by Django 3.1.2 on 2020-10-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0002_student_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
    ]
