# Generated by Django 3.1.2 on 2020-10-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main2', '0003_remove_student_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Talabalar', 'verbose_name_plural': 'Talaba'},
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
